#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "Execute $@"

  if [[ dry == "1" ]]; then
    return
  fi

  "$@"
}

log "------- dev-env -------"

copy_dir() {
  to=$2

  pushd $1
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
  for dir in $dirs; do
    execute rm -rf $to/$1/$dir
    execute cp -r $dir $to/$1/$dir
  done
  popd
}

copy_dir .config $HOME
